name: C CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential valgrind

      - name: Build debug
        run: make clean && make debug

      - name: Run tests (ASan + UBSan + LeakSanitizer)
        env:
          ASAN_OPTIONS: detect_leaks=1:abort_on_error=1
          UBSAN_OPTIONS: print_stacktrace=1
        run: make test

      - name: Build release
        run: make clean && make release

      - name: Run Valgrind
        run: make valgrind
